/**
 * @ecollective/knowledge-graph — the shared model of the eCollective Knowledge Graph.
 *
 * Read `SPEC.md` first. This package is the code side of that contract: Zod schemas for
 * every entity and value object (§3), the `ekgId` helpers (§4), the artifact types (§8),
 * the framework registry (§6.2), resource URL identity (§4.4), audience ratings (§7.4),
 * integrity helpers (§8.5), the whole-graph validator (§11), the commons' reference entities
 * (§3.9), import bundles (§9.7) and the change feed (§8.6).
 */

export {
  EKG_ID_PATTERN,
  EKG_TYPES,
  GRAPH_EKG_ID_PATTERN,
  GRAPH_TYPES,
  REFERENCE_TYPES,
  ULID_PATTERN,
  anyEkgId,
  ekgId,
  graphEkgId,
  isEkgId,
  isEkgIdOf,
  isEkgType,
  isGraphType,
  isReferenceType,
  mintEkgId,
  parseEkgId,
} from './ekg-id.js';
export type { EkgId, EkgType, GraphType, ReferenceType } from './ekg-id.js';

export {
  ASSESSMENT_KINDS,
  AUDIENCE_DESCRIPTORS,
  AUDIENCE_RATINGS,
  COSTS,
  COURSE_KINDS,
  EVIDENCE_CLASSES,
  EXTERNAL_ID_KEY_PATTERN,
  EXTERNAL_ID_SCHEMES,
  EMBED_POLICIES,
  LEVELS,
  MODALITIES,
  PROVENANCE_SOURCES,
  RELATIONS,
  RESOURCE_KINDS,
  RESOURCE_SUBKINDS,
  SEGMENT_KINDS,
  SEMVER_PATTERN,
  SLUG_PATTERN,
  STATUSES,
  SUBKIND_KINDS,
  VOLATILITIES,
  alignment,
  artifact,
  artifactResource,
  artifactSegment,
  assessment,
  audience,
  commons,
  course,
  credential,
  domain,
  entity,
  evidenceSignals,
  externalIds,
  outcome,
  provenance,
  resource,
  segment,
  semver,
  slug,
  sourceCitation,
  status,
  superseded,
  transcript,
  wikilink,
  withSubKindRule,
} from './schema.js';
export type {
  Alignment,
  ArtifactAssessment,
  ArtifactCourse,
  ArtifactCredential,
  ArtifactDomain,
  ArtifactEntity,
  ArtifactNode,
  ArtifactOutcome,
  ArtifactResource,
  ArtifactSegment,
  Assessment,
  AssessmentKind,
  Audience,
  AudienceDescriptor,
  AudienceRating,
  Cost,
  Course,
  CourseKind,
  Credential,
  Domain,
  EmbedPolicy,
  Entity,
  EvidenceClass,
  EvidenceSignals,
  ExternalIds,
  Level,
  Modality,
  Outcome,
  Provenance,
  ProvenanceSource,
  Relation,
  Resource,
  ResourceKind,
  ResourceSubKind,
  Segment,
  SegmentKind,
  SourceCitation,
  Status,
  Transcript,
  Volatility,
} from './schema.js';

export {
  ARTIFACT_PATHS,
  ARTIFACT_PREFIX,
  ARTIFACT_VERSION,
  CACHE_CONTROL,
  FEED_CHANGES,
  FEED_LIMIT,
  SCHEMA_VERSION,
  changelog,
  changelogDomainCounts,
  changelogEntry,
  checksums,
  domainFile,
  edge,
  feed,
  feedEntry,
  manifest,
  manifestDomain,
  sha256Hex as sha256HexSchema,
} from './artifact.js';
export type {
  Changelog,
  ChangelogEntry,
  Checksums,
  DomainFile,
  Edge,
  Feed,
  FeedChange,
  FeedEntry,
  Manifest,
} from './artifact.js';

export { sha256Hex, verifyChecksums } from './checksums.js';
export type { ChecksumMismatch } from './checksums.js';

export {
  FRAMEWORKS,
  FRAMEWORK_KINDS,
  STATE_FRAMEWORK_ID_PATTERN,
  frameworkById,
  frameworkByName,
  frameworkByNameLoosely,
  isStateFrameworkId,
} from './frameworks.js';
export type { Framework, FrameworkKind } from './frameworks.js';

export { DEGREE_LEVELS, STANDARD_KINDS, outcomeMapping, reference, referenceCommons } from './reference.js';
export type {
  DegreeLevel,
  OutcomeMapping,
  ReferenceEntity,
  ReferenceFramework,
  ReferenceInstitution,
  ReferenceOffering,
  ReferencePlatform,
  ReferenceProgram,
  ReferenceStandard,
  StandardKind,
} from './reference.js';

export {
  CONTRIBUTOR_IDENTITY_PATTERN,
  DEDUPE_DECISIONS,
  IMPORT_BUNDLE_VERSION,
  IMPORT_DECISIONS,
  LOCAL_ID_PATTERN,
  PROPOSAL_COLLECTIONS,
  REGISTERED_IDENTITIES,
  REJECTION_REASONS,
  bundleRef,
  dedupeEvidence,
  importBundle,
  importProducer,
  importReport,
  importReportItem,
  isLocalId,
  isRegisteredIdentity,
  localId,
  producerIdentity,
  proposals,
  qualityProposal,
  validateImportBundle,
} from './import-bundle.js';
export type {
  DedupeEvidence,
  ImportBundle,
  ImportBundleValidation,
  ImportDecision,
  ImportProducer,
  ImportReport,
  ImportReportItem,
  ProposalCollection,
  QualityProposal,
  RegisteredIdentity,
  RejectionReason,
} from './import-bundle.js';

export { normalizeResourceUrl, sameResourceUrl } from './url.js';

export { validateDomainFile, validateGraph } from './validate.js';
export type {
  DomainFileValidation,
  RefMode,
  Severity,
  ValidateOptions,
  ValidationError,
  ValidationResult,
} from './validate.js';
